### PR TITLE
Latest Trivy Version

### PR DESCRIPTION
**Pull request by SUSTAPLE117**
To test latest version

### CODE REVIEW

**Comment by fproulx-boostsecurity** [comment]
Fully smoke tested here https://github.com/boost-sandbox/module-tests-trivy/actions/runs/8072225493

**Review by fproulx-boostsecurity — APPROVED** [review]

**Comment by SUSTAPLE117** [comment]
@fproulx-boostsecurity smoke tests all fail we nned to upgrade the sbom converter

**Comment by fproulx-boostsecurity** [comment]
image
Oh yeah

**Comment by SUSTAPLE117** [comment]
Superseded  by other PRs

**Pull request closed without merging**
